# services:
#   chrome:
#     image: selenium/node-chrome:4.26.0-20241101
#     shm_size: 4gb
#     depends_on:
#       - selenium-hub
#     environment:
#       - SE_EVENT_BUS_HOST=selenium-hub
#       - SE_EVENT_BUS_PUBLISH_PORT=4442
#       - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#       - SE_ENABLE_TRACING=false
#     sysctls:
#       - net.ipv6.conf.all.disable_ipv6=1

#   selenium-hub:
#     image: selenium/hub:4.26.0-20241101
#     container_name: selenium-hub
#     ports:
#       - "4442:4442"
#       - "4443:4443"
#       - "4444:4444"

# services:
#   selenium:
#     image: selenium/standalone-firefox:4.26.0-20241101
#     shm_size: 4gb
#     network_mode: "host"
#     environment:
#       SE_ENABLE_TRACING: "false"  # Desactiva trazas
#       OTEL_EXPORTER_OTLP_ENDPOINT: ""  # Desactiva OpenTelemetry

services:
  firefox:
    image: selenium/standalone-firefox:4.26.0-20241101
    shm_size: 4gb
    network_mode: "host"
    ports:
      - 4444:4444
    environment:
      - START_XVFB=false
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
      - SE_SCREEN_DEPTH=24
      - STUN_SERVERS=stun:stun.l.google.com:19302,stun:stun1.l.google.com:19302
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    volumes:
      - /dev/shm:/dev/shm

  selenium-hub:
    image: selenium/hub:4.26.0-20241101
    container_name: selenium-hub
    network_mode: "host"
    environment:
      - GRID_BROWSER_TIMEOUT=3000
      - GRID_TIMEOUT=3000